# Data args
data_dir: /mnt/hieu/msmarco
train_file: msmarco_hard.jsonl
val_file: msmarco_dev.jsonl
num_workers: 20

# Model args
model_name_or_path: GritLM/GritLM-7B
use_bidirectional: False
attn_implementation: sdpa
normalized: True
pooling_method: mean
loss_gen_type: mixed
temperature: 0.07
# Lora setting
use_lora: True
train_adapter_name: msmarco
lora_r: 16
lora_alpha: 32
lora_dropout: 0.0
# Quantization setting
quantization: True

# Training args
# Machine args
nodes: 1
devices: 4
master_addr: localhost
master_port: "12345"

# Training args
seed: 1234
precision: bf16-true
mode: dpoc

# FSDP args
strategy: fsdp
sharding_strategy: full_shard
use_cpu_offload: True
use_activation_cpu_offload: True
no_sync: True
low_memory: True
reentrant_checkpointing: True

#Training data args
global_batch_size: 128
mini_batch_size: 1
max_seq_length: 2048
num_train_epochs: 3
max_steps: 5000
num_positive_samples: 1
num_negative_samples: 32
topk_neg: 8

# Gradcache settings
use_gc: True 
gc_mini_batch_size: 1

# Objective args
prompt_loss_weight: 0.05
use_miner: False
dpo_loss_type: sigmoid
dpo_beta: 0.1
label_smoothing_factor: 0.1

# Optimizer args
learning_rate: 0.0002 # 2e-4
warmup_steps: 100
apply_gradient_clipping: False
grad_norm_clip: 0.3
gradient_checkpointing: False

# Checkpointing args
logger_name: wandb
output_dir: output/checkpoints/mistral-7b-dpoc_msmarco
save_interval: 1000
log_interval: 1





