# Data args
data_name: msmarco
data_dir: dataset/msmarco
train_file: msmarco_hard.jsonl
val_file: msmarco_test.jsonl
num_workers: 4

# Model args
model_name_or_path: mistralai/Mistral-7B-Instruct-v0.2
pretrained_type: mistral
use_bidirectional: True
attn_implementation: sdpa
normalized: True
pooling_method: mean
loss_gen_type: mixed
temperature: 0.07
# Lora setting
use_lora: True
emb_adapter_name: emb_msmarco
lora_r: 16
lora_alpha: 32
lora_dropout: 0.1
# Quantization setting
quantization: False

# Training args
seed: 2708
precision: bf16-true

# FSDP args
strategy: fsdp
sharding_strategy: full_shard
use_cpu_offload: True
no_sync: True
low_memory: True

#Training data args
global_batch_size: 576
mini_batch_size: 1
max_seq_length: 2048
num_train_epochs: 1
max_steps: 500
num_positive_samples: 1
num_negative_samples: 1 
topk_neg: 1

# Gradcache settings
use_gc: True
gc_mini_batch_size: 8

# Objective args
prompt_loss_weight: 0.0
gen_loss_weight: 0.5
kl_loss_weight: 1.0
use_miner: True
dpo_loss_type: sigmoid
dpo_beta: 0.1
label_smoothing_factor: 0.1

# Optimizer args
learning_rate: 0.0002 # 2e-4@512
warmup_steps: 100
apply_gradient_clipping: False
grad_norm_clip: 0.3
gradient_checkpointing: True

# Checkpointing args
logger_name: wandb
save_interval: 50
log_interval: 1





