# Data args
# Data args
data_name: genclm
data_dir: dataset/GenCLM_v2/hard
val_file: dataset/msmarco/msmarco_test.jsonl
num_workers: 8

# Model args
model_name_or_path: microsoft/phi-1_5
pretrained_type: phi
use_bidirectional: True
attn_implementation: flash_attention_2
normalized: True
pooling_method: mean
loss_gen_type: mixed
temperature: 0.1
# Lora setting
use_lora: True
gen_adapter_name: gen_msmarco
lora_r: 16
lora_alpha: 32
lora_dropout: 0.1
# Quantization setting
quantization: False

# Training args
seed: 2708
precision: bf16-true

# FSDP args
strategy: fsdp
sharding_strategy: full_shard
use_cpu_offload: False
no_sync: True
low_memory: True

#Training data args
max_data_samples: 100000
global_batch_size: 512
mini_batch_size: 16
max_seq_length: 512
num_train_epochs: 1
max_steps: 200
num_positive_samples: 1
num_negative_samples: 1 

# Objective args
prompt_loss_weight: 0.0

# Optimizer args
learning_rate: 0.0001 
 
apply_gradient_clipping: False
grad_norm_clip: 0.3
gradient_checkpointing: False

# Checkpointing args
logger_name: wandb
save_interval: 100
log_interval: 1





